### ISSUE TITLE
pareto_discovery.py issue

### ISSUE THREAD

**Issue by Dwood0403** [yunshengtian/DGEMO#1]
I'm not sure how to fix this error when I run the example: python main.py --problem dtlz1 --n-var 6 --n-obj 2 --n-iter 20

File "main.py", line 57, in <module>
    main()
  File "main.py", line 45, in main
    X_next, Y_next = next(solution)
  File "C:\User\DGEMO-master\mobo\mobo.py", line 105, in solve
    solution = self.solver.solve(surr_problem, X, Y)
  File "C:\User\DGEMO-master\mobo\solver\solver.py", line 36, in solve
    algo = self.algo_type(sampling=sampling, **self.algo_kwargs)
  File "C:\User\DGEMO-master\mobo\solver\pareto_discovery\pareto_discovery.py", line 376, in __init__
    self.initialization = Initialization(sampling,
TypeError: __init__() got an unexpected keyword argument 'individual'

**Comment by yunshengtian** [comment]
Hi, this is because one of our dependency packages "pymoo" has updated to the 0.4.2 version, while we use the 0.4.0 version in our repository. So we recommend installing all the dependencies by anaconda using our provided environment.yml. Or I can compose a requirements.txt for pure pip installation later.

**Comment by Dwood0403** [comment]
Makes sense. Thank you.

**Comment by yunshengtian** [comment]
You're welcome! Thank you for your interest in our work.
